[고준영]users detail View
wecode-bootcamp-korea/24-1st-RS-backend pull request #17
Opened 2021-09-07 02:00 UTC by jay95ko

get, patch, delete 사용

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 유저 디테일에 관한 view구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- PR분리
- GET -> 유저정보 받아오기
- PATCH -> 유저정보 수정
- DELETE -> 유저 deacticate

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-07 09:20 UTC, lordmyshepherd requested changes

2021-09-07 09:20 UTC, lordmyshepherd commented on users/views.py
> +        return JsonResponse({"Result": result}, status=200)
이미 request 객체에 user가 담겨있기 때문에 또 다시 user를 호출할 필요가 없을 것 같네요~
```suggestion
        user = request.user
        
        result = {
            "name"           : user.name,
            "email"          : user.email,
            "is_sms_agree"   : user.is_sms_agree,
            "is_email_agree" : user.is_email_agree,
        }
        
        return JsonResponse({"Result": result}, status=200)
```

2021-09-07 09:20 UTC, lordmyshepherd commented on users/views.py
> +            )
```suggestion
            request.user.password = decoded_hashed_password
            request.user. is_sms_agree = ..
            request.user. is_email_agree = ..
            request.user.save()

```

2021-09-07 09:20 UTC, lordmyshepherd commented on users/views.py
> +        user.update(deactivated_at = now)
?? 동작하는 코드인가요?

2021-09-07 12:07 UTC, jay95ko commented on users/views.py
> +        return JsonResponse({"Result": result}, status=200)
놓친부분이었습니다!! 감사합니다!

2021-09-07 12:08 UTC, jay95ko commented on users/views.py
> +        user.update(deactivated_at = now)
동작하도록 수정하였습니다!

2021-09-07 12:08 UTC, jay95ko commented
File change 확인하였습니다.
리뷰 부탁드립니다

2021-09-08 01:20 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-08 01:20 UTC, merged