users.views.py 추가
wecode-bootcamp-korea/24-1st-RS-backend pull request #6
Opened 2021-09-01 10:59 UTC by fall031-muk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- users.views.py 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원가입 기능 구현하였습니다.
- email, password 유효성 검사, password 암호화, password 확인, sms/email 수신 동의 체크 등

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-02 01:57 UTC, lordmyshepherd requested changes

2021-09-02 01:57 UTC, lordmyshepherd commented on users/views.py
> +                is_email_agree    = 'False'
인풋으로 받을때 아래와 같이 받으면, line 38~ line 46 코드가 필요 없을 것 같네요~

```python
{
    "is_sms_check" : False
    "is_sms_check" : True
}
```

```suggestion
```

2021-09-02 06:31 UTC, fall031-muk commented on users/views.py
> +                is_email_agree    = 'False'
해당부분 회원가입 시 체크하면 콘솔쪽에  on, off로 나와서 위와 같이 T/F로 바꾸어 준 내용인데요, 현재 프론트쪽에서는 merge가 된 상태인데, 로직이 비효율적이거나 맞지 않다면 다시 상의해서 수정하는게 좋을까요...?

2021-09-02 07:23 UTC, fall031-muk commented on users/views.py
> +                is_email_agree    = 'False'
해당 데이터 True/False로 받아서 저장하는 방법으로 수정하였습니다!

2021-09-03 01:29 UTC, lordmyshepherd commented
LGTM 👍

2021-09-03 01:29 UTC, merged

2021-09-03 01:54 UTC, fall031-muk commented
매우 감사드립니다!!!