login 기능 추가
wecode-bootcamp-korea/24-1st-RS-backend pull request #9
Opened 2021-09-03 03:56 UTC by fall031-muk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 기능 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 로그인 시 이메일, 비밀번호 입력 및 로그인 성공 시 토큰 발급

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-03 09:58 UTC, lordmyshepherd requested changes

2021-09-03 09:58 UTC, lordmyshepherd commented on users/views.py
> +
`User.objects.get(email=data['email'])` 코드가 중복되네요. 중복되는 문제도 있지만, `objects.get()` method를 호출할 때마다 데이터베이스에 요청을 보냅니다. 그렇기 때문에 아래와 같이 한번만 호출해서 데이터베이스에서 가져온 값을 user 변수에 저장(메모리에 올려놓고)해서 사용할 수 있도록 수정해주세요~

```suggestion
            if not User.objects.filter(email=data['email']).exists():
                return JsonResponse({"MESSAGE":"INVALID_USER"}, status=401)
            user = User.objects.get(email=data['email'])
            
            if bcrypt.checkpw(..):
                    access_token = jwt.encode({'id':user ..}, SECRET_KEY, algorithm=ALGORITHM)
                    return JsonResponse({"MESSAGE":"SUCCESS","ACCESS_TOKEN":access_token}, status=201)
            
```

2021-09-03 10:24 UTC, fall031-muk commented on users/views.py
> +
알려주신 방식으로 user에 정보 저장하여 사용하는 방법으로 수정하였습니다!!
많은 가르침 감사드립니다 :)

2021-09-06 01:37 UTC, lordmyshepherd commented
LGTM 👍

2021-09-06 01:37 UTC, merged